### ISSUE TITLE
Некоторые изменения

### ISSUE THREAD

**Issue by Frikikiki** [lordeup/BrokenLinkFinder#7]
- В Parser.java `private ParserState setState(String str)` -> `private ParserState getState(String str)`

- В Parser.java `private void checkState(String str, ParserState state)` -> `private void runStateCase(String str, ParserState state)`

- Улучшить парсинг аргументов командной строки, рассмотрев как можно больше различных вариантов написания аргументов пользователем

**Comment by lordeup** [comment]
Исправлено
